apiVersion: apps/v1
kind: Deployment
metadata:
  name: weber-insight
  namespace: demo
  labels:
    app: weber-insight
spec:
  selector:
    matchLabels:
      app: weber-insight
  template:
    metadata:
      labels:
        app: weber-insight
    spec:
      imagePullSecrets:
        - name: nodeflux-registry
      containers:
        - name: weber-insight
          image: registry.gitlab.com/nodefluxio/demo-apps/weber/insight:latest
          imagePullPolicy: Always
          env:
            - name: APP_HOST
              value: "0.0.0.0"
            - name: APP_PORT
              value: "8080"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: weber
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: weber
                  key: db_password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: weber
                  key: db_name
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: weber
                  key: db_demo
            - name: DB_PORT
              value: "5432"
          ports:
            - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: weber-insight
  namespace: demo
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: weber-insight

---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: weber-insight
  namespace: demo
spec:
  host: admin.demo.nodeflux.io
  service: weber-insight.demo
  bypass_auth: true
  timeout_ms: 30000
